### ISSUE TITLE
Command Comments 

### ISSUE THREAD

**Issue by ChasingCode34** [LakotaRobotics1038/2024RobotProject#31]
From what I understand, these are the commands we are planning to utilize. I have put some descriptions and some of my comments. If my understanding is incorrect about something, let me know. Also, if you have any questions, comment down below.

- Acquire Command - Uses the acquisition mechanism to acquire a note with sensor input

- [ ] Create another command for detecting the note (Detect Note Command)?

- Lift (Climber) Depress Command - Lowers the lifter to the starting position

- [ ] What kind of sensors would detect it has reached this position? Would utilizing a PID controller and encoder be a better option? If we are using pneumatics, what adjustments will we need to make?

- Lift (Climber) Extend Command - Extends the lifter to reach the chains

- [ ] What kind of sensors would detect it has reached this position? Would utilizing a PID controller and encoder be a better option? If we are using pneumatics, what adjustments will we need to make?

- Score Note Command - Runs the scoring mechanism to score the note

- [ ] Can we detect when the note leaves the robot using sensors and stop the motors once it has been released?

- Scoring Position Command - Raisers or lowers the scoring mechanism to a specified position depending on the location to score
- Storage Run Command - Runs the storage mechanism’s motor to transport the note from the acquisition mechanism to the scoring mechanism

- [ ] Can we also use sensor input here to detect when a note has arrived at the scoring mechanism? Otherwise, will we need a timer to determine when to stop the storage motors?

- Leave Starting Area Command - Follows trajectory to leave the starting area to earn 2 points

- [ ] Necessary?

- [ ] Copy “Leave Community Auto” Code from 2023

- [ ] Detect April Tag Command - Uses the vision system to detect an April Tag and aligns the robot based on its relative position to the April Tag
- [ ] Future (if possible): Deposit In Trap Command - Deposit a note using the scoring mechanism into the trap on the stage
- [ ] Future (if possible): Score in Speaker - Launch a note using the scoring mechanism into the speaker

**Comment by matunkar** [comment]
> PID Controller + encoder for the lift
for the moment, there's no way to guarantee we'll be positioned in the same way in front of the chain each time. probably when we get a command to center on the stage AprilTag we will need to update it

> Score note command sensors
 there will (most likely) be a limit switch at the end of the scoring mechanism before the note reaches the roller - but in terms of knowing exactly when the note leaves the roller, it will likely be a timer. 

> storage run command sensors
yes! we will have a limit switch for that i believe. at some point (when sensors are finalized) there will be a (probably a single) issue to update all subsystems to add sensors. and then probably multiple issues to update the commands.

> leave starting area command
that wouldnt be a command it'd be an auton. in terms of auton planning i actually need to talk with you and wes about that. the pathplanner application updated, and now it's possible to add commands within the software. so we need to decide what we're going to do - either do our auton planning (entirely) in pathplanner or use command groups like we did last year.

> detect april tag command
> detect note command
both of those are going to come a bit later i think. people will hopefully start practicing java integration for vision tables soon (working on getting the robot to respond to input from vision, maybe using old data from last year?), and then when the model is built we can start testing.
