### ISSUE TITLE
prototype robot code

### ISSUE THREAD

**Issue by matunkar** [LakotaRobotics1038/2024RobotProject#65]
ports: 
- [x]  scoring roller - 60
- [x]  storage L - 61
- [x] storage R - 56
- [x] transition - 58
- [x] acquisition - 57

commands (should be based on issue 57, we should not need to remove the sensors): 
- [x]   acquisition command
- [x]   take the storage subsystem +command from issue 57
- [x]   take the transition command from issue 57

joystick:
all of these are forward
- [x] steal from the joystick issue (23?) 
- [x] A button - run scoring roller
- [x] B button - run storage
- [x] X button - run transition
- [x] Y button - run acquisition

this should not be pushed to main. once we start testing there will probably be a new issue for bugfixes.

**Comment by reediculous456** [comment]
No PR attached, back to developer. Also, prototype code should not be merged to main. If we learned anything about the code during prototyping, it should be copied to a fresh branch that does not change port numbers, motor types, or anything else specific to only the prototype
