### ISSUE TITLE
Selector for April Tags

### ISSUE THREAD

**Issue by ChasingCode34** [LakotaRobotics1038/2024RobotProject#76]
- [ ] Create a selector for us to choose which April tags we want to detect during the Auton section of the match based on our alliance.
- [ ] If possible, restrict options based on which auton routine we run.
- [ ] Change April tag   ##IDs for ScoreInAmp Auton to 5.

**Comment by Griffin9881** [comment]
wouldn't this happen automatically when selecting an auton, it wouldn't go on a different path each time

**Comment by Griffin9881** [comment]
i dont think a selector is nessesary
